### PR TITLE
Adding launcher icon

### PR DESCRIPTION
**Pull request by sakshivij**
Adding Icons #7

### CODE REVIEW

**Comment by SAITARUN55** [comment]
LGTM (Looks Good to Me) but it would have been great if you had done the same for iOS

**Comment by sakshivij** [comment]
Hey can I create an issue for same and work on it ?

**Comment by SAITARUN55** [comment]
Okay, I will close the previous issue

**Comment by sakshivij** [comment]
Thanks! Created a new issue. Can you please assign it to.me ?.

**Comment by SAITARUN55** [comment]
Sure, Good Luck

**Pull request merged**
