### PR TITLE
Added Login via Gmail Feature  #2

### PR DESCRIPTION
**Pull request by shivaniaakanksha**
shifted to AndroidX
Added Gmail Login Using Firebase.

### CODE REVIEW

**Comment by shivaniaakanksha** [comment]
> shifted to AndroidX
> Added Gmail Login Using Firebase.

@SAITARUN55 
https://github.com/SAITARUN55/metroapp/issues/2#issuecomment-603038068
Please Review.

**Review by viveky259259 — COMMENTED** [review]
Remove firebase_analytics for now

**Comment by shilpi1958** [comment]
@sakshivij are you still working on it?

**Comment by sakshivij** [comment]
@shilpi this issue most probably was taken by someone else and already done with. Changes have not been merged most probably

**Comment by SAITARUN55** [comment]
@shilpi1958 This is pr...she has already taken and made changes and pushed it too...but there were issues while running the application

**Comment by shivaniaakanksha** [comment]
@SAITARUN55  can you please look into this and try to solve the conflicts as its too delayed now.

**Comment by SAITARUN55** [comment]
> @SAITARUN55 can you please look into this and try to solve the conflicts as its too delayed now.

mostly by tomorrow, I will

**Comment by prasadsunny1** [comment]
I'll look into this and fix your PR @shivaniaakanksha

**Comment by SAITARUN55** [comment]
@prasadsunny1 There is no JSON file and there are errors while running...she took the analytics from pubspec but there is a file related to analytics... I thought she will push the JSON but that also will be a problem for me if she does it...

**Comment by SAITARUN55** [comment]
> @prasadsunny1 There is no JSON file and there are errors while running...she took the analytics from pubspec but there is a file related to analytics... I thought she will push the JSON but that also will be a problem for me if she does it...

The problem while running is its about SDK version to upgrade whereas in her system it's running very effectively, but I am unable to update the same in my system

**Comment by shivaniaakanksha** [comment]
> @prasadsunny1 There is no JSON file and there are errors while running...she took the analytics from pubspec but there is a file related to analytics... I thought she will push the JSON but that also will be a problem for me if she does it...

I pushed the JSON file but it is in .gitignore , I have shared the files on slack.

**Comment by prasadsunny1** [comment]
Add your own json file

**Comment by prasadsunny1** [comment]
JSON should not be pushed into git

**Comment by sakshivij** [comment]
I tested the repo. The issue is something related to firebase analytics. Even though it has been removed. If it's fine I can work on this.. since I'm halfway done.

**Comment by sakshivij** [comment]
Or totally up to you guys as well. Depends on how you all want to take this.

**Comment by shivaniaakanksha** [comment]
> > @prasadsunny1 There is no JSON file and there are errors while running...she took the analytics from pubspec but there is a file related to analytics... I thought she will push the JSON but that also will be a problem for me if she does it...
> 
> The problem while running is its about SDK version to upgrade whereas in her system it's running very effectively, but I am unable to update the same in my system

Try upgrading SDK in pubspec.yaml to
> sdk: ">=2.5.0 <3.0.0"

**Comment by SAITARUN55** [comment]
> > > @prasadsunny1 There is no JSON file and there are errors while running...she took the analytics from pubspec but there is a file related to analytics... I thought she will push the JSON but that also will be a problem for me if she does it...
> > 
> > 
> > The problem while running is its about SDK version to upgrade whereas in her system it's running very effectively, but I am unable to update the same in my system
> 
> Try upgrading SDK in pubspec.yaml to
> 
> > sdk: ">=2.5.0 <3.0.0"

Did that also...but no use

**Pull request closed without merging**
